GET http://localhost:5266/games

###
GET http://localhost:5266/games/4

###
POST http://localhost:5266/games
Content-Type: application/json

{
  "name": "Final Fantasy XIV",
  "genreId": 2,
  "price": 59.99,
  "releaseDate": "2010-09-30"
}

###
PUT http://localhost:5266/games/1
Content-Type: application/json

{
  "name": "The Last of Us Part II Turbo",
  "genre": "Action-adventure",
  "price": 39.99,
  "releaseDate": "2020-06-19"
}

###
DELETE http://localhost:5266/games/1